<?php
/**
 * @file
 * Code for the Proud Payment feature.
 */

include_once 'proud_payment.features.inc';

/**
 * Implements hook_menu().
 */
function proud_payment_menu() {
  $items['admin/proud/payment'] = array(
    'title' => 'Proud payment settings',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('configure proud'),
    'page arguments' => array('proud_payment_admin_form'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'proud_payment.admin.inc',
  );

  return $items;
}
